name: PR Build Check

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Print Node and Bun versions
        run: |
          echo "Node version: $(node -v)"
          echo "Bun version: $(bun -v)"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          bun install

      - name: Create dummy env file
        run: |
          touch .env.local
          echo "NEXT_PUBLIC_SUPABASE_URL=https://dummy-project.supabase.co" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1bW15IiwiZHVtbXkiOnRydWV9.dummy" >> .env.local
          echo "OPENAI_API_KEY=sk-dummy-key-for-build-test" >> .env.local

      - name: Build project with debug
        run: |
          echo "Starting build..."
          export NODE_ENV=production
          bun --bun next build --debug
        env:
          CI: true

      - name: Report status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Build successful! PR can be merged."
          else
            echo "❌ Build failed. Please fix the issues before merging."
            echo "Debug information:"
            echo "Node modules contents:"
            ls -la node_modules
            echo "Package versions:"
            bun pm ls
            exit 1
          fi
